---------------------------------------- SHOW ----------------------------------------
{
  errors: [
    ContextualError: There was an error in the extension "anonymous" (use named functions to improve this error message) while running hook "encode".
        at runPipeline (/some/path/to/runPipeline.ts:76:18)
        at async Object.run (/some/path/to/main.ts:286:22)
        at async run (/some/path/to/client.ts:256:20)
        at async executeRootType (/some/path/to/client.ts:185:12)
        at async executeRootTypeField (/some/path/to/client.ts:216:20)
        at async <anonymous> (/some/path/to/output|output_envelope_envelope-error__envelope-error.ts:24:16) {
      context: {
        hookName: 'encode',
        source: 'extension',
        extensionName: 'anonymous'
      },
      cause: Error: Something went wrong.
          at <anonymous> (/some/path/to/output|output_envelope_envelope-error__envelope-error.ts:20:9)
          at applyBody (/some/path/to/main.ts:310:28)
    }
  ]
}